### ISSUE TITLE
Royalty issues with marketplaces using ERC2981

### ISSUE THREAD

**Issue by cblanquera** [cblanquera/mintpress#1]
The current spec looks like the following.

```js
interface IERC2981 is IERC165 {
  /// @notice Called with the sale price to determine how much royalty
  //          is owed and to whom.
  /// @param _tokenId - the NFT asset queried for royalty information
  /// @param _salePrice - the sale price of the NFT asset specified by _tokenId
  /// @return receiver - address of who should be sent the royalty payment
  /// @return royaltyAmount - the royalty payment amount for _salePrice
  function royaltyInfo(
    uint256 _tokenId,
    uint256 _salePrice
  ) external view returns (
    address receiver,
    uint256 royaltyAmount
  );
}
```

This only returns one receiver rather than a list of receivers. The [2981](https://github.com/ethereum/EIPs/issues/2907) rationale for this is because you can return a `PaymentSplitter` contract but the gas to deploy this contract looks like the following in Ethereum.

```
·----------------------------|---------------------------|-------------|-----------------------------·
|    Solc version: 0.8.9     ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 12450000 gas  │
·····························|···························|·············|······························
|  Methods                   ·              200 gwei/gas               ·       4530.89 usd/eth       │
··············|··············|·············|·············|·············|···············|··············
|  Deployments               ·                                         ·  % of limit   ·             │
·····························|·············|·············|·············|···············|··············
|  PaymentSplitter           ·          -  ·          -  ·     542191  ·        4.4 %  ·     491.32  │
·----------------------------|-------------|-------------|-------------|---------------|-------------·
```

and like this on Polygon.

```
·----------------------------|---------------------------|-------------|-----------------------------·
|    Solc version: 0.8.9     ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 12450000 gas  │
·····························|···························|·············|······························
|  Methods                   ·              200 gwei/gas               ·       1.98 usd/matic        │
··············|··············|·············|·············|·············|···············|··············
|  Deployments               ·                                         ·  % of limit   ·             │
·····························|·············|·············|·············|···············|··············
|  PaymentSplitter           ·          -  ·          -  ·     542191  ·        4.4 %  ·       0.21  │
·----------------------------|-------------|-------------|-------------|---------------|-------------·
```

This effects linking NFTs on OpenSea and Mintable particularly, though definitely could be more.

**Comment by cblanquera** [comment]
For posterity, this is something we cannot fix because the spec is already adopted and I agree sux. The general advice if you are planning to link your NFT to these kind of platforms is to either 

 - Make sure there is only one royalty recipient
 - Make a PaymentSplitter or smart wallet that distributes the funds 
 - Only list on Rarible and other marketplaces that support multi royalties

**Comment by cblanquera** [comment]
Not to say that we won't fix this per se. I'm open for contributions on this. My only concern is gas.

**Comment by cliffhall** [comment]
@cblanquera Although the cost to deploy a funds splitter contract might be high, that doesn't mean an architecture that implements them bears such a cost for every contract. If a funds splitter implementation is the same for every collaboration then you can just clone an already deployed contract as a minimal proxy at a far lower cost. I should have touched on this over on the 2981 discussion when I mentioned the funds splitter approach.

[Here's an example](https://github.com/knownorigin/known-origin-contracts-v3/blob/master/contracts/spikes/collaborators/clone/CloneBasedRegistry.sol#L30) I built for KnownOrigin.

**Comment by MaxflowO2** [comment]
> 
> 
> @cblanquera Although the cost to deploy a funds splitter contract might be high, that doesn't mean an architecture that implements them bears such a cost for every contract. If a funds splitter implementation is the same for every collaboration then you can just clone an already deployed contract as a minimal proxy at a far lower cost. I should have touched on this over on the 2981 discussion when I mentioned the funds splitter approach.
> 
> [Here's an example](https://github.com/knownorigin/known-origin-contracts-v3/blob/master/contracts/spikes/collaborators/clone/CloneBasedRegistry.sol#L30) I built for KnownOrigin.

Shows a 404, I work primarily on other chains (Fantom seems to be my go to for now), I do this frequently, but yet you could call the contract as abstract and have the contract be the payment splitter itself...

[My source](https://github.com/MaxflowO2/ERC2981/blob/master/contracts/modules/PaymentSplitter.sol)

Yes it's a rewrite of it, but functions the same, but on the contract you are deploying. Depending on what you desire, you can almost modify anything to do anything.

**Comment by cliffhall** [comment]
> Shows a 404,

The example I linked above? This works for me: https://github.com/knownorigin/known-origin-contracts-v3/blob/master/contracts/spikes/collaborators/clone/CloneBasedRegistry.sol#L30

The concern here is the cost to deploy a payment splitter contract for every collaboration. The PaymentSplitter you pointed to looks fine, but if it costs 500 bucks to deploy it for each collab, that's prohibitive. So you just deploy it once and then use a factory that creates minimal clone proxies that treat the splitter as implementation. That gets the price down to a reasonable proposition.

**Comment by MaxflowO2** [comment]
> 
> 
> > Shows a 404,
> 
> The example I linked above? This works for me: https://github.com/knownorigin/known-origin-contracts-v3/blob/master/contracts/spikes/collaborators/clone/CloneBasedRegistry.sol#L30

Still does, could be a private repo, but agree on Ethereum, so are you calling a proxy each time to a deployed copy? Seriously after our first chats, you got my knowledge base steadily increasing with proxies, do want to say thank you for that, it's like a whole new world now.

**Comment by cblanquera** [comment]
> If a funds splitter implementation is the same for every collaboration then you can just clone an already deployed contract as a minimal proxy at a far lower cost. I should have touched on this over on the 2981 discussion when I mentioned the funds splitter approach.

In this project, the royalties are defined per token class not for the entire contract and allows them to be different from each other. So if payment splitter, people using this project would need to deploy different versions of it every single time *(or maybe just reconfigure it every time)*.

So if 100 token classes and PaymentSplitter, then deploy this contract as well as 100 other PaymentSplitter contracts.

> The example I linked above? This works for me: https://github.com/knownorigin/known-origin-contracts-v3/blob/master/contracts/spikes/collaborators/clone/CloneBasedRegistry.sol#L30

Yes sir it's a 404 for me.
 
> The concern here is the cost to deploy a payment splitter contract for every collaboration. The PaymentSplitter you pointed to looks fine, but if it costs 500 bucks to deploy it for each collab, that's prohibitive. So you just deploy it once and then use a factory that creates minimal clone proxies that treat the splitter as implementation. That gets the price down to a reasonable proposition.

Thanks @cliffhall for giving me a possible direction I can work on. 

@MaxflowO2 we are all relatively new to this, let's figure this out together :D

**Comment by cliffhall** [comment]
@cblanquera 
> Yes sir it's a 404 for me.

Woops. Sorry, that repo used to be public. 

I've created [a gist that is a little more concise](https://gist.github.com/cliffhall/94aec29237b3045295eb204e25189176).

This example shows a a factory/registry for deploying cheap, minimal clones of royalty funds handler logic and retrieving those clones by token address and id.

Note that it does nothing to attempt to manage the royalty percentage associated with any given NFT as that's a different rabbit hole. Nor does it proscribe exactly how a funds handler should work. This gist only concerns itself with being able to:

1.  Maintain a mapping of named funds handler logic contracts to the their addresses
2. Clone and initialize a named funds handler contract for a given NFT and its recipients and their relative shares
3. Provide lookup by token address and id of the associated funds handler clone (a minimal proxy)
